
CREATE TABLE STORE (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL,
  PHOTO_PATH VARCHAR(100) NOT NULL,
  NUM_CHECKOUTS INTEGER NOT NULL,
  DATE_CREATED DATETIME  NOT NULL
);

CREATE TABLE TILL (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME INTEGER NOT NULL,
  ACTUAL_TURN INTEGER -- FK
);

CREATE TABLE QUEUE (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  ID_STORE INTEGER NOT NULL,
  QUEUE_TYPE VARCHAR(10) NOT NULL,
  PRIORITY INTEGER(1) NOT NULL
);

CREATE TABLE BUCKET_QUEUE (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  ID_STORE INTEGER NOT NULL, -- FK
  ID_DESTINATION_QUEUE INTEGER NOT NULL,
  QUEUE_TYPE VARCHAR(10) NOT NULL,
  PRIORITY INTEGER(1) NOT NULL
);

CREATE TABLE BUCKET (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  ID_BUCKET_QUEUE INTEGER NOT NULL,
  HOUR_START DATETIME NOT NULL,
  HOUR_FINAL DATETIME NOT NULL,
  QUANTITY INTEGER(1) NOT NULL
);

CREATE TABLE TURN (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NUMBER INTEGER NOT NULL,
  ID_BUCKET INTEGER,
  ID_USER INTEGER,
  ID_QUEUE INTEGER,
  DATE_TURN DATETIME NOT NULL,
  STATE VARCHAR(10) NOT NULL
);

-- FK --

ALTER TABLE QUEUE ADD FOREIGN KEY (ID_STORE) REFERENCES STORE(ID);
ALTER TABLE BUCKET ADD FOREIGN KEY (ID_QUEUE) REFERENCES BUCKET_QUEUE(ID);
ALTER TABLE BUCKET_QUEUE ADD FOREIGN KEY (ID_STORE) REFERENCES STORE(ID);

ALTER TABLE TURN ADD FOREIGN KEY (ID_BUCKET) REFERENCES BUCKET(ID);
ALTER TABLE TURN ADD FOREIGN KEY (ID_QUEUE) REFERENCES QUEUE(ID);

-- STORE DATA --

INSERT INTO STORE (NAME, DATE_CREATED) VALUES ('Carnisseria', NOW());
INSERT INTO STORE (NAME, DATE_CREATED) VALUES ('Peixateria', NOW());
INSERT INTO STORE (NAME, DATE_CREATED) VALUES ('Sushi', NOW());
INSERT INTO STORE (NAME, DATE_CREATED) VALUES ('Xarcuteria', NOW());
INSERT INTO STORE (NAME, DATE_CREATED) VALUES ('Forn de pa', NOW());

-- QUEUE DATA --

INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (1, 'VIP', 0);
INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (1, 'MOBILES', 1);
INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (1, 'TOTEM', 2);

INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (2, 'VIP', 0);
INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (2, 'MOBILES', 1);
INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (2, 'TOTEM', 2);

INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (3, 'VIP', 0);
INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (3, 'MOBILES', 1);
INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (3, 'TOTEM', 2);

INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (4, 'VIP', 0);
INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (4, 'MOBILES', 1);
INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (4, 'TOTEM', 2);

INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (5, 'VIP', 0);
INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (5, 'MOBILES', 1);
INSERT INTO QUEUE (ID_STORE, QUEUE_TYPE, PRIORITY) VALUES (5, 'TOTEM', 2);

-- TURNS DATA --

INSERT INTO TURN (NUMBER, ID_BUCKET, ID_USER, ID_QUEUE, DATE_TURN, STATE) VALUES (1, NULL, 0, 3, NOW(), 'WAITING');
INSERT INTO TURN (NUMBER, ID_BUCKET, ID_USER, ID_QUEUE, DATE_TURN, STATE) VALUES (2, NULL, 0, 3, NOW(), 'WAITING');
INSERT INTO TURN (NUMBER, ID_BUCKET, ID_USER, ID_QUEUE, DATE_TURN, STATE) VALUES (3, NULL, 0, 3, NOW(), 'WAITING');
INSERT INTO TURN (NUMBER, ID_BUCKET, ID_USER, ID_QUEUE, DATE_TURN, STATE) VALUES (4, NULL, 0, 3, NOW(), 'WAITING');
